import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { Otel } from '@/components/otel';
import './globals.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const {
    BUILD: version,
    OTEL_SERVICE_NAME: serviceName,
    OTEL_EXPORTER_OTLP_ENDPOINT: endpoint
  } = process.env;

  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Otel endpoint={endpoint!} serviceName={serviceName!} version={version!} />
      </body>
    </html>
  )
}
