import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { headers } from "next/headers";

import { Nav } from '@/components/nav';
import { Otel } from '@/components/otel';
import './globals.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const headersList = await headers();

  // see https://www.w3.org/TR/trace-context/#traceparent-header
  const traceparent = headersList.get("traceparent");

  // the spec (https://www.w3.org/TR/trace-context/#parent-id) prescribes 
  const [traceVersion, traceId, parentId, traceFlags] = traceparent?.split("-") || [];

  const {
    BUILD: version,
    OTEL_SERVICE_NAME: serviceName,
    OTEL_EXPORTER_OTLP_ENDPOINT: endpoint,
  } = process.env;

  return (
    <html lang="en">
      <head>
        {/*
        https://www.w3.org/TR/trace-context/
        Set the `traceparent` in the server's HTML template code. It should be
        dynamically generated server side to have the server's request trace Id,
        a parent span Id that was set on the server's request span, and the trace
        flags to indicate the server's sampling decision
        (01 = sampled, 00 = notsampled).
        '{version}-{traceId}-{spanId}-{sampleDecision}
      */}

        {
          // `Vendors MUST ignore the traceparent when the parent-id is invalid`
          parentId && parentId !== "0000000000000000" && (
            <meta
              name="traceparent"
              content={`00-ab42124a3c573678d4d8b21ba52df3bf-d21f7bc17caa5aba-01`}
            ></meta>
          )
        }
      </head>
      <body className={inter.className}>
        <Nav />
        <main className="p-5">{children}</main>
        <Otel
          endpoint={endpoint!}
          serviceName={serviceName!}
          version={version!}
        />
      </body>
    </html>
  );
}
